#  写在开头：本篇文章是作者在复习线性代数时对常用运算python代码实现的一些总结

In [1]:
import numpy as np

##  一. ndarray常用运算

##  1.1 获取多维数组的行数、列数...以及维度、元素总数（以二维数组为例）

In [2]:
array_dim2=np.array([[1,2,3],[4,5,6],[7,8,9]])
array_dim2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [3]:
np.shape(array_dim2)[0]   #获取行数

3

In [4]:
np.shape(array_dim2)[1]   #获取列数

3

In [5]:
np.ndim(array_dim2)   #获取维度   注：维度就是shape元组的长度，此处shape元组是（3,3）

2

In [6]:
np.size(array_dim2)   #获取元素总个数

9

##  1.2 对数组中元素求和(多维数组可以指定对列求和还是对行求和）

In [7]:
array_dim2=np.array([[1,2,3],[4,5,6],[7,8,9]])
array_dim2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [8]:
np.sum(array_dim2)    #对全部数求和

45

In [9]:
np.sum(array_dim2,axis=0)  #对列求和

array([12, 15, 18])

In [10]:
np.sum(array_dim2,axis=1)  #对行求和

array([ 6, 15, 24])

## 1.3 对数组中的元素求平方根

In [11]:

np.set_printoptions(precision=4)  #控制一下输出位数
np.sqrt(array_dim2)

array([[1.    , 1.4142, 1.7321],
       [2.    , 2.2361, 2.4495],
       [2.6458, 2.8284, 3.    ]])

##  二.向量基本运算

##  2.1 向量点积运算

In [12]:
vec1=np.array([1,2,3])
vec1

array([1, 2, 3])

In [13]:
vec2=np.array([4,5,6])
vec2

array([4, 5, 6])

In [14]:
dot_product1=(vec1*vec2).sum()  #基于numpy元素逐个运算的机制
dot_product1

32

In [15]:
dot_product2=np.dot(vec1,vec2)  #numpy库自带，建议使用这个，代码可读性强一点
dot_product2

32

## 1.2 求向量的模

In [16]:
vec=np.array([3,4,5])
vec

array([3, 4, 5])

In [17]:
norm_vec1=np.sqrt((vec**2).sum())     #基于numpy元素逐个运算的机制
norm_vec1

7.0710678118654755

In [18]:
norm_vec2=np.linalg.norm(vec)          #numpy库自带，建议使用这个，代码可读性强一点
norm_vec2

7.0710678118654755

##  三.矩阵基本运算

##  3.1 矩阵乘法

In [20]:
matrix_1=[[1,2,3],[4,5,6]]
matrix_1

[[1, 2, 3], [4, 5, 6]]

In [22]:
matrix_2=[[3,4],[5,6],[7,8]]
matrix_2

[[3, 4], [5, 6], [7, 8]]

In [23]:
np.matmul(matrix_1,matrix_2) # matmul-matrix multiplication(矩阵乘法)

array([[34, 40],
       [79, 94]])